name: main-workflow
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/npm@master
        with:
          args: install
      - uses: actions/setup-node@v1
        with:
          arquitecture: 'x64'
      - run: npm install
      - run: npm start

